services:
  photo-slam-ros:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        USERNAME: ${USERNAME}
        HOSTNAME: ${HOSTNAME}
        USER_PASSWORD: ${USER_PASSWORD}
    image: photo-slam-ros:latest
    network_mode: host
    cpus: 16
    mem_limit: 24g
    ipc: host
    pid: host
    user: "${USERNAME}:${USER_GID}"
    hostname: ${HOSTNAME}
    stdin_open: true
    tty: true
    working_dir: /home/${USERNAME}
    command: /bin/bash
    runtime: nvidia
    privileged: true
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - USERNAME=${USERNAME}
      - ROS_DOMAIN_ID=0
      - DISPLAY=unix${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../:/home/${USERNAME}/projects/Photo-SLAM-ROS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/${USERNAME}/.Xauthority:rw
      - ${HOME}/.ssh:/home/${USERNAME}/.ssh:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
